### ISSUE TITLE
Support GitHub Pages

### ISSUE THREAD

**Issue by piecioshka** [robreczarek/test-chaining-calculator#6]
1. Settings
2. Scroll down to section "GitHub Pages"
3. Select source "master"
4. Wait 30 seconds
5. Enter to http://robreczarek.github.io//test-chaining-calculator/app/
6. Inform me 😄

**Comment by robreczarek** [comment]
@piecioshka we have liftoff 🚀

**Comment by piecioshka** [comment]
@robreczarek bosko! 👍

**Comment by piecioshka** [comment]
@robreczarek you can add this link on main page of repository, due to example https://github.com/piecioshka/warsawjs-workshop-slider

**Comment by robreczarek** [comment]
@piecioshka Here ya go: https://github.com/robreczarek/test-chaining-calculator#demo
